[package]
name = "humansort-cli"
authors = ["Bradley Gannon <bradley@bradleygannon.com>"]
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
humansort-lib = { path = "../humansort-lib" }
serde_json = "1.0.90"
