[package]
name = "humansort-lib"
authors = ["Bradley Gannon <bradley@bradleygannon.com>"]
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1.0.151", features = ["derive"] }
