[package]
name = "humansort-lib"
authors = ["Bradley Gannon <bradley@bradleygannon.com>"]
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
getrandom = { version = "0.2.8", features = ["js"] }
rand = "0.8.5"
serde = { version = "1.0.151", features = ["derive"] }
